# Generated by Django 3.1.5 on 2021-03-24 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lyric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=144)),
                ('song_writer', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=144)),
                ('timestamp', models.SlugField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verse', models.CharField(max_length=1024)),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
        migrations.CreateModel(
            name='Chorus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chorus', models.CharField(max_length=1024)),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
        migrations.CreateModel(
            name='Bridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brige', models.CharField(max_length=1024)),
                ('lyric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lyrics.lyric')),
            ],
        ),
    ]
