# Generated by Django 5.0 on 2024-01-20 11:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lyric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unique_num", models.UUIDField(default=uuid.uuid4, unique=True)),
                ("title", models.CharField(max_length=144)),
                ("song_writer", models.CharField(max_length=50)),
                ("slug", models.SlugField(max_length=144)),
                ("timestamp", models.SlugField(max_length=144)),
            ],
        ),
        migrations.CreateModel(
            name="Chorus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chorus", models.TextField(max_length=1024)),
                (
                    "lyric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lyrics.lyric"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Bridge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bridge", models.TextField(max_length=1024)),
                (
                    "lyric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lyrics.lyric"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Verse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("verse", models.TextField(max_length=1024)),
                (
                    "lyric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="lyrics.lyric"
                    ),
                ),
            ],
        ),
    ]
