# Generated by Django 3.1.7 on 2021-03-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0002_auto_20210324_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bridge',
            name='bridge',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='chorus',
            name='chorus',
            field=models.TextField(max_length=1024),
        ),
        migrations.AlterField(
            model_name='verse',
            name='verse',
            field=models.TextField(max_length=1024),
        ),
    ]
